#lang eopl
(define (number->sequence num)
  (list num '() '()))
(define (current-element seq)
  (car seq))
(define (move-to-left seq)
  (list (car (list-ref seq 1))
        (cdr (list-ref seq 1))
        (cons (current-element seq)
              (list-ref seq 2))))
(define (move-to-right seq)
  (list (car (list-ref seq 2))
        (cons (current-element seq)
              (list-ref seq 1))
        (cdr (list-ref seq 2))))
