#lang eopl
(define (empty-env)
  (lambda (signal)
    (cond
      ((eqv? signal 'empty) #t)
      ((eqv? signal 'apply) 'none)
      ((eqv? signal 'has-binding?) (lambda (var) #f))
      (else (eopl:error 'empty-env "Unknown method")))))
(define (extend-env saved-var saved-val saved-env)
  (lambda (signal)
    (cond
      ((eqv? signal 'empty) #f)
      ((eqv? signal 'apply)
       (lambda (search-var)
         (if (eqv? search-var saved-var)
             saved-val
             (apply-env saved-env search-var))))
      ((eqv? signal 'has-binding?)
       (lambda (search-var)
         (eqv? search-var saved-var)))
      (else (eopl:error "Unknown method")))))  
(define (apply-env env search-var)
  ((env 'apply) search-var))
(define (empty-env? env)
  (env 'empty))
(define (has-binding? env search-var)
  ((env 'has-binding?) search-var))