#lang eopl
(define (empty-stack)
  (lambda (signal)
    (cond
      ((eqv? signal 'top) 'none)
      ((eqv? signal 'pop) (empty-stack))
      ((eqv? signal 'empty?) #t)
      (else (eopl:error 'empty-stack "Unknown method")))))
(define (push value stack)
  (lambda (signal)
    (cond
      ((eqv? signal 'top) value)
      ((eqv? signal 'pop) stack)
      ((eqv? signal 'empty?) #f)
      (else (eopl:error 'push "Unknown method")))))
(define (pop stack)
  (stack 'pop))
(define (top stack)
  (stack 'top))
(define (empty-stack? stack)
  (stack 'empty?))