#lang eopl
(require "syntax-tree.scm")
(define (parse-tree tree)
  (define (parse-pair tree)
    (define (nullary-op? head)
      (eqv? head 'emptylist))
    (define (extract-nullary head)
      head)
    (define (binary-op? head)
      (or (eqv? head '+)
          (eqv? head '-)
          (eqv? head '*)
          (eqv? head 'equals?)
          (eqv? head 'greater?)
          (eqv? head 'less?)
          (eqv? head 'cons)))
    (define (extract-binary head)
      head)
    (define (unary-op? head)
      (or
       (eqv? head 'zero?)
       (eqv? head 'negate)
       (eqv? head 'car)
       (eqv? head 'cdr)
       (eqv? head 'null?)))
    (define (extract-unary head)
      head)
    (define (nary-op? head)
      (or
       (eqv? head 'list)
       (eqv? head 'cond)))
    (define (extract-nary head)
      head)
    (define (extract-nary-mapper head)
      (define (parse-cond tree)
        (list (parse-tree (list-ref tree 0))
              (parse-tree (list-ref tree 1))))
      (cond
        ((eqv? head 'list) parse-tree)
        ((eqv? head 'cond) parse-cond)))
    (define (parse-let tree)
      (define (extract-let-var tree)
        (list-ref (list-ref tree 1) 0))
      (define (extract-let-expr tree)
        (list-ref (list-ref tree 1) 1))
      (define (extract-let-body tree)
        (list-ref tree 2))
      (let-exp (extract-let-var tree)
               (parse-tree (extract-let-expr tree))
               (parse-tree (extract-let-body tree))))
    (let ((head (car tree)))
      (cond
        ((binary-op? head) (binop-exp (extract-binary head) (parse-tree (list-ref tree 1))
                                  (parse-tree (list-ref tree 2))))
        ((unary-op? head) (unary-op-exp (extract-unary head) (parse-tree (list-ref tree 1))))
        ((nary-op? head) (nary-exp (extract-nary head) (map (extract-nary-mapper head) (cdr tree))))
        ((eqv? 'if head) (if-exp (parse-tree (list-ref tree 1))
                                 (parse-tree (list-ref tree 2))
                                 (parse-tree (list-ref tree 3))))
        ((eqv? 'let head) (parse-let tree))
        ((nullary-op? head) (nullary-op-exp (extract-nullary head)))
        (else (eopl:error 'parse-tree "Invalid syntax")))))
  (cond
    ((null? tree) (eopl:error 'parse-tree "Empty string"))
    ((pair? tree) (parse-pair tree))
    ((number? tree) (int-exp tree))
    ((symbol? tree) (var-exp tree))
    ((eqv? 'true tree) (bool-exp #t))
    ((eqv? 'false tree) (bool-exp #f))
    (else (int-exp tree))))
(provide parse-tree)
